# Generated by Django 3.0.5 on 2021-01-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(default='', max_length=100)),
                ('Actors', models.CharField(default='', max_length=300)),
                ('Director', models.CharField(default='', max_length=200)),
                ('Genre', models.CharField(default='', max_length=200)),
                ('Duration', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
